### ISSUE TITLE
Running test on Firefox v67.0.1 receives errors.

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-test#82]
When running tests of `test JES Explorer - should launch app correctly`, the test failed with error:

```
UnsupportedOperationError: User prompt of type promptUserAndPass is not supported
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:542:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

So far this happens on Firefox v67.0.1.

**Comment by jackjia-ibm** [comment]
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1556307
